services:
  - type: web
    name: hostyria-host
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hostyria-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: hostyria-db
    plan: free
